### ISSUE TITLE
Android compatibility issues: regex parsing and `JSONObject.keySet()`

### ISSUE THREAD

**Issue by HanzoDev1375** [karlvr/js-beautify-java#2]

**Comment by karlvr** [comment]
@HanzoDev1375 hiya, can you please provide some details about what's happening for you? I'm not an Android developer so my ability to assist with Android will be limited. But if you can provide details maybe we can solve it. Or a PR is welcome.

**Comment by HanzoDev1375** [comment]
> @HanzoDev1375 hiya, can you please provide some details about what's happening for you? I'm not an Android developer so my ability to assist with Android will be limited. But if you can provide details maybe we can solve it. Or a PR is welcome.

The problem is that when I compile your code, the program gets an error.

![Screenshot_2025-06-08-10-17-38-855_com.miui.bugreport.jpg](https://github.com/user-attachments/assets/04c66eb3-d08d-4758-bd88-cb08b399bf10)

![Screenshot_2025-06-08-10-12-51-806_com.miui.bugreport.jpg](https://github.com/user-attachments/assets/fb8e389a-448c-4cc9-80c0-2537a1f46fd1)

**Comment by HanzoDev1375** [comment]
We strongly recommend that you use the Gson library instead of org.json... It has better interaction, is faster and more accurate, and also has better compatibility with Java versions. Now there is no KeySet in your code. Well, in Android, even if we import the jar, the program gives an error because its method is not there and it is not registered in Gradle because it is internal to the SDK.

**Comment by karlvr** [comment]
@HanzoDev1375 are you sure you're using the 1.14.11 version of this library? The line number in the stack trace doesn't match the regex that has anything like `{{{` in it, which is unexpected.

I've just released 1.15.4, which is synced up with upstream.

I haven't changed from `org.json`. I am not aware of any inaccuracies in that implementation. I have upgraded it for good measure. Also, it is only used for some methods of updating the `Options` configuration object, so it's not actually used at runtime unless you're using that feature.

Please let me know if this fault still exists in the latest (1.15.4) release.

**Comment by HanzoDev1375** [comment]
@karlvr I tried but it still didn't work for Android. Try testing it in an Android test app. Download Android Studio from the developers' site.

**Comment by karlvr** [comment]
@HanzoDev1375 I’m sorry I don’t have time to test this on Android. If you could please confirm you’re using the 1.15.4 version, and provide the updated stack trace I will happily take a look.

**Comment by HanzoDev1375** [comment]
> [@HanzoDev1375](https://github.com/HanzoDev1375) I’m sorry I don’t have time to test this on Android. If you could please confirm you’re using the 1.15.4 version, and provide the updated stack trace I will happily take a look.

Well I checked and it still showed me the same error
The best option is antlr4

**Comment by HanzoDev1375** [comment]
![Image](https://github.com/user-attachments/assets/c3ef5846-935b-46f6-859d-be22f972d093)

This is the result of the new test.

I should also mention that keySet is not in the Android json library, I updated it.

```java
public void apply(JSONObject data) {
      Iterator<String> keys = data.keys();
      while (keys.hasNext()) {
        String key = keys.next();
        if (!apply(key, data)) {
          throw new IllegalArgumentException("Unsupported options key: " + key);
        }
      }
    }

    protected boolean apply(String key, JSONObject data) {
      try {

        switch (key) {
          case "indent_size":
            indent_size = data.getInt(key);
            return true;
          case "disabled":
            disabled = data.getBoolean(key);
            return true;
          case "html":
            html().apply(data.getJSONObject(key));
            return true;
          case "css":
            css().apply(data.getJSONObject(key));
            return true;
          case "js":
            js().apply(data.getJSONObject(key));
            return true;
        }
      } catch (JSONException err) {

      }
      return false;
    }
```
I think the error is here in Android.

**Comment by karlvr** [comment]
@HanzoDev1375 Thanks for this; this doesn't appear to be related to the regex error though? Is this a separate issue? You mention the Android json library... are you using a different version to the library specified in the `pom.xml` for this package?

**Comment by HanzoDev1375** [comment]
Android has the Json library in its SDK by default. I tried to update it, but the SDK ignores it. Yes, the error is related to the same part I sent you.

**Comment by trinhnguyenm** [comment]
Hi @HanzoDev1375 @karlvr 

Solution: Escape curly braces in regex patterns for Android compatibility
I encountered and successfully resolved this issue in my Android project. The root cause is that Android's Pattern.compile() requires proper escaping of curly braces {} in regex patterns, unlike standard Java regex.

Problem:
```
// This fails on Android with PatternSyntaxException
Pattern.compile("--}}")  // Unescaped } causes syntax error
```
Solution:
```
// Escape all curly braces with double backslashes
Pattern.compile("--\\}\\}")  // Works correctly on Android
```
Complete fix example:
```
// Before (fails on Android):
handlebars_comment = pattern_reader.starting_with(Pattern.compile("\\{\\{!--")).until_after(Pattern.compile("--}}"));
```

```
// After (works on Android):
handlebars_comment = pattern_reader.starting_with(Pattern.compile("\\{\\{!--")).until_after(Pattern.compile("--\\}\\}"));
```
Root cause analysis:
Standard Java: Treats {} as literal characters in most contexts
Android Pattern.compile(): Stricter parsing, requires explicit escaping of {}
Impact: Any regex with unescaped {} throws PatternSyntaxException on Android
Comprehensive fix needed:
All patterns in the codebase containing {} need escaping:

```
%} → %\\}
#} → #\\}
*} → *\\}
{literal} → \\{literal\\}
{/literal} → \\{/literal\\}
```
This ensures cross-platform compatibility between standard Java and Android environments.

**Comment by karlvr** [comment]
@trinhnguyenm thank you very much for that. I've pushed a change... are you able to test it @HanzoDev1375 without me making a release?

**Comment by HanzoDev1375** [comment]
> [@trinhnguyenm](https://github.com/trinhnguyenm) thank you very much for that. I've pushed a change... are you able to test it [@HanzoDev1375](https://github.com/HanzoDev1375) without me making a release?
It seems to work well, but we should also note that keySet is not in the org.json.JSONOBJECT package in the Android version, so you need to think of another way.

**Comment by karlvr** [comment]
@HanzoDev1375 thanks for the quick response; I've changed it out for `.keys()`. Please let me know if that works for you in entirety now.

**Comment by HanzoDev1375** [comment]
> @HanzoDev1375 thanks for the quick response; I've changed it out for `.keys()`. Please let me know if that works for you in entirety now.



If you changed it then it **works**, thanks.

**Comment by karlvr** [comment]
I have published version 1.15.4.1 with these changes. Thanks for your help improving this package.
